<a href="https://colab.research.google.com/github/makms2023/ds1002-ntr8qx/blob/main/homework/week-6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Homework - Week 6

Complete the following blocks as specified in the directions. Run each cell to return the desired output. Save your notebook back to your GitHub repository and submit the GitHub URL for your notebook for review.

# Pandas

## 1. Fetch and Load Data
In class we created a DataFrame using the `read_csv` method. Go to https://catalog.data.gov/dataset/electric-vehicle-population-data and download the CSV format of the "Electric Vehicle Population Data" dataset. Then upload it to Google Colab.

Load that data into a Pandas DataFrame and display the first 20 rows. Show your work.

In [2]:
# Set up pandas and populate the dataframe above using the raw data. Then continue to work with the dataframe in the questions below.
import pandas as pd
df=pd.read_csv("Electric_Vehicle_Population_Data.csv")

In [4]:
# Format a command that how many rows and columns are in this dataset.
df.shape

(150482, 17)

In [21]:
# Format a command that displays every other row of records 1000 through 1999, and the columns "City", "State", "Model Year", and "Make".
for x in range(1000,1999):
  print(df.loc[x, ["City","State","Model Year","Make"]])
  x=x+2

City          Auburn
State             WA
Model Year      2022
Make           TESLA
Name: 1000, dtype: object
City           Kent
State            WA
Model Year     2018
Make          TESLA
Name: 1001, dtype: object
City          Vancouver
State                WA
Model Year         2021
Make               JEEP
Name: 1002, dtype: object
City          Newcastle
State                WA
Model Year         2022
Make              TESLA
Name: 1003, dtype: object
City          Edmonds
State              WA
Model Year       2022
Make            TESLA
Name: 1004, dtype: object
City          Kirkland
State               WA
Model Year        2015
Make             TESLA
Name: 1005, dtype: object
City          Kirkland
State               WA
Model Year        2013
Make              FORD
Name: 1006, dtype: object
City          Issaquah
State               WA
Model Year        2016
Make            NISSAN
Name: 1007, dtype: object
City          Seattle
State              WA
Model Year       2022
Make              KIA
Name: 1008, dtype: object
City           Kent
State            WA
Model Year     2023
Make          TESLA
Name: 1009, dtype: object
City            Olympia
State                WA
Model Year         2013
Make          CHEVROLET
Name: 1010, dtype: object
City          Vancouver
State                WA
Model Year         2018
Make              TESLA
Name: 1011, dtype: object
City          Seattle
State              WA
Model Year       2019
Make            TESLA
Name: 1012, dtype: object
City          Bellevue
State               WA
Model Year        2019
Make            NISSAN
Name: 1013, dtype: object
City          Seattle
State              WA
Model Year       2017
Make             FIAT
Name: 1014, dtype: object
City          Seattle
State              WA
Model Year       2022
Make            TESLA
Name: 1015, dtype: object
City          Bainbridge Island
State                        WA
Model Year                 2017
Make                  CHEVROLET
Name: 1016, dtype: object
City          North Bend
State                 WA
Model Year          2022
Make            POLESTAR
Name: 1017, dtype: object
City          Kirkland
State               WA
Model Year        2022
Make               BMW
Name: 1018, dtype: object
City          Vancouver
State                WA
Model Year         2021
Make                BMW
Name: 1019, dtype: object
City          Redmond
State              WA
Model Year       2018
Make            TESLA
Name: 1020, dtype: object
City          Bothell
State              WA
Model Year       2023
Make              KIA
Name: 1021, dtype: object
City          Seattle
State              WA
Model Year       2023
Make          HYUNDAI
Name: 1022, dtype: object
City          Seattle
State              WA
Model Year       2021
Make            TESLA
Name: 1023, dtype: object
City          Bothell
State              WA
Model Year       2022
Make            TESLA
Name: 1024, dtype: object
City          Seattle
State              WA
Model Year       2020
Make            VOLVO
Name: 1025, dtype: object
City          Shoreline
State                WA
Model Year         2023
Make              TESLA
Name: 1026, dtype: object
City          Seattle
State              WA
Model Year       2014
Make              BMW
Name: 1027, dtype: object
City          Redmond
State              WA
Model Year       2023
Make            TESLA
Name: 1028, dtype: object
City          Bellevue
State               WA
Model Year        2017
Make               BMW
Name: 1029, dtype: object
City          Kirkland
State               WA
Model Year        2013
Make             TESLA
Name: 1030, dtype: object
City          Seatac
State             WA
Model Year      2022
Make           TESLA
Name: 1031, dtype: object
City          Bellevue
State               WA
Model Year        2015
Make             TESLA
Name: 1032, dtype: object
City          Kirkland
State               WA
Model Year        2023
Make             TESLA
Name: 1033, dtype: object
City             Tukwila
State                 WA
Model Year          2023
Make          MITSUBISHI
Name: 1034, dtype: object
City            Kirkland
State                 WA
Model Year          2019
Make          VOLKSWAGEN
Name: 1035, dtype: object
City          Seattle
State              WA
Model Year       2018
Make            TESLA
Name: 1036, dtype: object
City          Woodinville
State                  WA
Model Year           2022
Make                TESLA
Name: 1037, dtype: object
City          Bellevue
State               WA
Model Year        2020
Make             TESLA
Name: 1038, dtype: object
City          Seattle
State              WA
Model Year       2017
Make             AUDI
Name: 1039, dtype: object
City          University Place
State                       WA
Model Year                2022
Make                     TESLA
Name: 1040, dtype: object
City          Seattle
State              WA
Model Year       2022
Make             AUDI
Name: 1041, dtype: object
City          Lynnwood
State               WA
Model Year        2021
Make             TESLA
Name: 1042, dtype: object
City               Kent
State                WA
Model Year         2020
Make          CHEVROLET
Name: 1043, dtype: object
City          Bremerton
State                WA
Model Year         2016
Make               FORD
Name: 1044, dtype: object
City          Redmond
State              WA
Model Year       2020
Make            TESLA
Name: 1045, dtype: object
City          Seattle
State              WA
Model Year       2019
Make            VOLVO
Name: 1046, dtype: object
City          Woodinville
State                  WA
Model Year           2023
Make              HYUNDAI
Name: 1047, dtype: object
City          Vancouver
State                WA
Model Year         2021
Make               MINI
Name: 1048, dtype: object
City          Bainbridge Island
State                        WA
Model Year                 2016
Make                      TESLA
Name: 1049, dtype: object
City          Issaquah
State               WA
Model Year        2022
Make          POLESTAR
Name: 1050, dtype: object
City          Port Orchard
State                   WA
Model Year            2021
Make                  FORD
Name: 1051, dtype: object
City          Seattle
State              WA
Model Year       2019
Make           TOYOTA
Name: 1052, dtype: object
City           Kent
State            WA
Model Year     2020
Make          TESLA
Name: 1053, dtype: object
City            Kirkland
State                 WA
Model Year          2022
Make          VOLKSWAGEN
Name: 1054, dtype: object
City          Seattle
State              WA
Model Year       2018
Make              BMW
Name: 1055, dtype: object
City          Issaquah
State               WA
Model Year        2020
Make            JAGUAR
Name: 1056, dtype: object
City          Longview
State               WA
Model Year        2018
Make               BMW
Name: 1057, dtype: object
City          Everett
State              WA
Model Year       2018
Make            TESLA
Name: 1058, dtype: object
City          Shoreline
State                WA
Model Year         2013
Make             NISSAN
Name: 1059, dtype: object
City          Kirkland
State               WA
Model Year        2020
Make             TESLA
Name: 1060, dtype: object
City          Seattle
State              WA
Model Year       2020
Make            TESLA
Name: 1061, dtype: object
City          Seatac
State             WA
Model Year      2023
Make           TESLA
Name: 1062, dtype: object
City          Bellevue
State               WA
Model Year        2019
Make              AUDI
Name: 1063, dtype: object
City          Auburn
State             WA
Model Year      2022
Make          RIVIAN
Name: 1064, dtype: object
City          Oak Harbor
State                 WA
Model Year          2015
Make              NISSAN
Name: 1065, dtype: object
City          Redmond
State              WA
Model Year       2020
Make            TESLA
Name: 1066, dtype: object
City            Renton
State               WA
Model Year        2022
Make          CHRYSLER
Name: 1067, dtype: object
City          Seattle
State              WA
Model Year       2021
Make           TOYOTA
Name: 1068, dtype: object
City          Redmond
State              WA
Model Year       2021
Make            TESLA
Name: 1069, dtype: object
City          Bellevue
State               WA
Model Year        2023
Make           HYUNDAI
Name: 1070, dtype: object
City          Seattle
State              WA
Model Year       2015
Make             FORD
Name: 1071, dtype: object
City          Bellevue
State               WA
Model Year        2021
Make           PORSCHE
Name: 1072, dtype: object
City          Bothell
State              WA
Model Year       2018
Make            TESLA
Name: 1073, dtype: object
City          Normandy Park
State                    WA
Model Year             2021
Make                  VOLVO
Name: 1074, dtype: object
City          Seattle
State              WA
Model Year       2023
Make            TESLA
Name: 1075, dtype: object
City            Camas
State              WA
Model Year       2022
Make          HYUNDAI
Name: 1076, dtype: object
City          Woodinville
State                  WA
Model Year           2016
Make               NISSAN
Name: 1077, dtype: object
City          Redmond
State              WA
Model Year       2021
Make            TESLA
Name: 1078, dtype: object
City              Renton
State                 WA
Model Year          2023
Make          VOLKSWAGEN
Name: 1079, dtype: object
City          Newcastle
State                WA
Model Year         2023
Make                KIA
Name: 1080, dtype: object
City            Kent
State             WA
Model Year      2020
Make          TOYOTA
Name: 1081, dtype: object
City            Seattle
State                WA
Model Year         2014
Make          CHEVROLET
Name: 1082, dtype: object
City              Burien
State                 WA
Model Year          2018
Make          MITSUBISHI
Name: 1083, dtype: object
City          Kirkland
State               WA
Model Year        2021
Make             TESLA
Name: 1084, dtype: object
City          Seatac
State             WA
Model Year      2022
Make           TESLA
Name: 1085, dtype: object
City          Auburn
State             WA
Model Year      2021
Make            FORD
Name: 1086, dtype: object
City          Vancouver
State                WA
Model Year         2018
Make              HONDA
Name: 1087, dtype: object
City          Kirkland
State               WA
Model Year        2022
Make               BMW
Name: 1088, dtype: object
City          Kirkland
State               WA
Model Year        2023
Make               BMW
Name: 1089, dtype: object
City          Bellevue
State               WA
Model Year        2023
Make            RIVIAN
Name: 1090, dtype: object
City          Battle Ground
State                    WA
Model Year             2023
Make                  TESLA
Name: 1091, dtype: object
City          Issaquah
State               WA
Model Year        2023
Make             TESLA
Name: 1092, dtype: object
City            Bellevue
State                 WA
Model Year          2021
Make          VOLKSWAGEN
Name: 1093, dtype: object
City          Seattle
State              WA
Model Year       2020
Make              KIA
Name: 1094, dtype: object
City          Kirkland
State               WA
Model Year        2023
Make             VOLVO
Name: 1095, dtype: object
City          Seatac
State             WA
Model Year      2018
Make             BMW
Name: 1096, dtype: object
City          Newcastle
State                WA
Model Year         2019
Make              TESLA
Name: 1097, dtype: object
City            Seattle
State                WA
Model Year         2012
Make          CHEVROLET
Name: 1098, dtype: object
City           Kent
State            WA
Model Year     2019
Make          TESLA
Name: 1099, dtype: object
City             Seattle
State                 WA
Model Year          2023
Make          VOLKSWAGEN
Name: 1100, dtype: object
City          Vancouver
State                WA
Model Year         2020
Make             TOYOTA
Name: 1101, dtype: object
City          Kirkland
State               WA
Model Year        2022
Make               BMW
Name: 1102, dtype: object
City          Kirkland
State               WA
Model Year        2022
Make              JEEP
Name: 1103, dtype: object
City          Vancouver
State                WA
Model Year         2022
Make                BMW
Name: 1104, dtype: object
City          Bainbridge Island
State                        WA
Model Year                 2014
Make                       FORD
Name: 1105, dtype: object
City          Vancouver
State                WA
Model Year         2018
Make          CHEVROLET
Name: 1106, dtype: object
City          Kirkland
State               WA
Model Year        2022
Make             TESLA
Name: 1107, dtype: object
City          Kirkland
State               WA
Model Year        2022
Make            NISSAN
Name: 1108, dtype: object
City          Renton
State             WA
Model Year      2023
Make           TESLA
Name: 1109, dtype: object
City          Seattle
State              WA
Model Year       2020
Make            TESLA
Name: 1110, dtype: object
City          Kirkland
State               WA
Model Year        2022
Make              FORD
Name: 1111, dtype: object
City          Bellevue
State               WA
Model Year        2019
Make             TESLA
Name: 1112, dtype: object
City          Bainbridge Island
State                        WA
Model Year                 2022
Make                      TESLA
Name: 1113, dtype: object
City          Mercer Island
State                    WA
Model Year             2023
Make                  TESLA
Name: 1114, dtype: object
City          Seattle
State              WA
Model Year       2023
Make              BMW
Name: 1115, dtype: object
City             Auburn
State                WA
Model Year         2021
Make          CHEVROLET
Name: 1116, dtype: object
City              Yelm
State               WA
Model Year        2021
Make          CHRYSLER
Name: 1117, dtype: object
City             Seattle
State                 WA
Model Year          2019
Make          VOLKSWAGEN
Name: 1118, dtype: object
City          Seattle
State              WA
Model Year       2021
Make             AUDI
Name: 1119, dtype: object
City          Seattle
State              WA
Model Year       2022
Make            TESLA
Name: 1120, dtype: object
City          Battle Ground
State                    WA
Model Year             2023
Make                  VOLVO
Name: 1121, dtype: object
City          Vancouver
State                WA
Model Year         2017
Make          CHEVROLET
Name: 1122, dtype: object
City          Bothell
State              WA
Model Year       2021
Make              BMW
Name: 1123, dtype: object
City          Kirkland
State               WA
Model Year        2022
Make              FORD
Name: 1124, dtype: object
City          Sequim
State             WA
Model Year      2023
Make             KIA
Name: 1125, dtype: object
City          Bellevue
State               WA
Model Year        2021
Make             TESLA
Name: 1126, dtype: object
City          Bellevue
State               WA
Model Year        2023
Make             TESLA
Name: 1127, dtype: object
City            Bellevue
State                 WA
Model Year          2023
Make          VOLKSWAGEN
Name: 1128, dtype: object
City          Seattle
State              WA
Model Year       2017
Make            VOLVO
Name: 1129, dtype: object
City          Kirkland
State               WA
Model Year        2022
Make             TESLA
Name: 1130, dtype: object
City          Vancouver
State                WA
Model Year         2013
Make          CHEVROLET
Name: 1131, dtype: object
City          Newcastle
State                WA
Model Year         2022
Make                KIA
Name: 1132, dtype: object
City          Toppenish
State                WA
Model Year         2013
Make             NISSAN
Name: 1133, dtype: object
City          Sammamish
State                WA
Model Year         2021
Make              TESLA
Name: 1134, dtype: object
City          Kirkland
State               WA
Model Year        2023
Make            NISSAN
Name: 1135, dtype: object
City          Kirkland
State               WA
Model Year        2012
Make             TESLA
Name: 1136, dtype: object
City          Bellevue
State               WA
Model Year        2021
Make             TESLA
Name: 1137, dtype: object
City          Seattle
State              WA
Model Year       2023
Make            TESLA
Name: 1138, dtype: object
City          Kirkland
State               WA
Model Year        2022
Make             TESLA
Name: 1139, dtype: object
City          North Bend
State                 WA
Model Year          2021
Make               TESLA
Name: 1140, dtype: object
City          Redmond
State              WA
Model Year       2020
Make            TESLA
Name: 1141, dtype: object
City          Issaquah
State               WA
Model Year        2021
Make            TOYOTA
Name: 1142, dtype: object
City            Seattle
State                WA
Model Year         2023
Make          CHEVROLET
Name: 1143, dtype: object
City          Seattle
State              WA
Model Year       2021
Make             FORD
Name: 1144, dtype: object
City          Bothell
State              WA
Model Year       2014
Make              BMW
Name: 1145, dtype: object
City          Shoreline
State                WA
Model Year         2020
Make              TESLA
Name: 1146, dtype: object
City           Tukwila
State               WA
Model Year        2023
Make          CHRYSLER
Name: 1147, dtype: object
City          Seattle
State              WA
Model Year       2016
Make           NISSAN
Name: 1148, dtype: object
City          Redmond
State              WA
Model Year       2018
Make            TESLA
Name: 1149, dtype: object
City          Port Orchard
State                   WA
Model Year            2022
Make               HYUNDAI
Name: 1150, dtype: object
City          Redmond
State              WA
Model Year       2014
Make           NISSAN
Name: 1151, dtype: object
City          Bremerton
State                WA
Model Year         2017
Make          CHEVROLET
Name: 1152, dtype: object
City          Vancouver
State                WA
Model Year         2023
Make              VOLVO
Name: 1153, dtype: object
City          Seattle
State              WA
Model Year       2023
Make            TESLA
Name: 1154, dtype: object
City          Bellevue
State               WA
Model Year        2022
Make             TESLA
Name: 1155, dtype: object
City          Kirkland
State               WA
Model Year        2019
Make             TESLA
Name: 1156, dtype: object
City          Seattle
State              WA
Model Year       2018
Make            TESLA
Name: 1157, dtype: object
City          Seattle
State              WA
Model Year       2018
Make            TESLA
Name: 1158, dtype: object
City          Newcastle
State                WA
Model Year         2017
Make              TESLA
Name: 1159, dtype: object
City          Vancouver
State                WA
Model Year         2018
Make             NISSAN
Name: 1160, dtype: object
City          Kenmore
State              WA
Model Year       2015
Make           NISSAN
Name: 1161, dtype: object
City          Kirkland
State               WA
Model Year        2018
Make            NISSAN
Name: 1162, dtype: object
City           Kirkland
State                WA
Model Year         2023
Make          CHEVROLET
Name: 1163, dtype: object
City          Issaquah
State               WA
Model Year        2023
Make             TESLA
Name: 1164, dtype: object
City          Poulsbo
State              WA
Model Year       2023
Make           NISSAN
Name: 1165, dtype: object
City          Bellevue
State               WA
Model Year        2023
Make             TESLA
Name: 1166, dtype: object
City          Bainbridge Island
State                        WA

# 2. Cleaning/Imputing Data

In class we reviewed methods for removing duplicate rows and handling empty cell values. Download [this data set](https://github.com/nmagee/ds1002/blob/main/data/very-messy-data.csv) and upload into Google Colab.

Create another Pandas DataFrame from that data and perform the following steps.

In [22]:
# Set up pandas and populate the dataframe above using the raw data. Then continue to work with the dataframe in the questions below.
import pandas as pd
df2=pd.read_csv("very-messy-data.csv")

In [23]:
# Write a snippet of code that will display the number of duplicate rows exist in the DF.
print(df2.duplicated().sum())

316

In [30]:
# Next, remove all duplicate rows using Python.
df2= df2.drop_duplicates()
df2

       id  sepal_length  sepal_width  petal_length  petal_width    species
0       1           3.5          2.9           1.4          0.5  virginica
1       2           3.6          3.2           3.0          0.5     setosa
2       3           3.8          NaN           2.2          1.5     setosa
3       4           5.8          2.7           2.6          1.2  virginica
4       5           4.9          3.6           3.0          1.2  virginica
..    ...           ...          ...           ...          ...        ...
995   996           4.5          3.6           NaN          2.7     setosa
996   997           4.0          2.1           NaN          2.1     setosa
997   998           5.9          2.5           2.1          2.5  virginica
998   999           5.0          2.6           1.9          NaN        NaN
999  1000           3.4          3.9           1.9          1.5     setosa

[1000 rows x 6 columns]

In [42]:
# For the FOUR columns involving sepal and petal length and width, update all NaN
# values with the column mean such that NO empty cells remain. This method
# is called "imputation" because it fills in cells in a statistically less-impactful
# way than if they were blank.

# Show how you would update those four columns in code
import numpy as np
df_filled = df2.fillna(df2.mean())
df_filled

<ipython-input-42-236a9216fd12>:8: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df_filled = df2.fillna(df2.mean())

       id  sepal_length  sepal_width  petal_length  petal_width    species
0       1           3.5     2.900000      1.400000     0.500000  virginica
1       2           3.6     3.200000      3.000000     0.500000     setosa
2       3           3.8     2.987694      2.200000     1.500000     setosa
3       4           5.8     2.700000      2.600000     1.200000  virginica
4       5           4.9     3.600000      3.000000     1.200000  virginica
..    ...           ...          ...           ...          ...        ...
995   996           4.5     3.600000      2.000442     2.700000     setosa
996   997           4.0     2.100000      2.000442     2.100000     setosa
997   998           5.9     2.500000      2.100000     2.500000  virginica
998   999           5.0     2.600000      1.900000     1.561863        NaN
999  1000           3.4     3.900000      1.900000     1.500000     setosa

[1000 rows x 6 columns]

# 3. Save to a New CSV

Preserve your updated DF to a CSV file by using the method built into Pandas.
Name the output file `very-clean-data.csv` and save it to GitHub in the same directory where you will save this homework. We will review both your Colab notebook and the cleaned data file.

In [46]:
df_filled.to_csv('very-clean-data.csv')